# Generated by Django 5.2.5 on 2025-08-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type_course',
            field=models.CharField(default='standard', max_length=100),
        ),
    ]
