# Generated by Django 5.2.5 on 2025-09-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_type_course_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForPageCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('fun_fact', models.CharField(max_length=255)),
                ('projects', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Course (Extended)',
                'verbose_name_plural': 'Courses (Extended)',
            },
            bases=('courses.course',),
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='topic',
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='courses.course')),
            ],
        ),
    ]
